name: Reusable Integration Tests

on:
  workflow_call:
    inputs:
      sqs_endpoint:
        required: true
        type: string

jobs:
  integration_test:
    runs-on: ubuntu-latest
    env:
      SQS_DOMAIN: ${{ inputs.sqs_endpoint }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
      - run: pytest -s -n auto
        working-directory: tests
