name: SQS Integration Test

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Enter comma-separated list of environments (e.g., stage,prod,eu).'
        required: true
        default: 'stage'
  schedule:
    - cron: '0 * * * *'

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate matrix for workflow_dispatch or schedule
        id: set-matrix
        run: |
          echo "Generating matrix..."
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo '{ "matrix": [' > matrix.json
            IFS=',' read -ra ADDR <<< "${{ github.event.inputs.environments }}"
            for env in "${ADDR[@]}"; do
              endpoint=$(jq -r --arg env "$env" '.[$env]' .github/workflows/env_mappings.json)
              if [[ -n "$endpoint" && "$endpoint" != "null" ]]; then
                echo "{\"env\":\"$env\", \"sqs_endpoint\":\"$endpoint\"}," >> matrix.json
              fi
            done
            echo "{}]}" >> matrix.json
            sed -i '$ s/},{}]$/}]/' matrix.json
          else
            jq -c 'to_entries | map({"env": .key, "sqs_endpoint": .value})' .github/workflows/env_mappings.json > matrix.json
          fi

          echo "Generated matrix.json content:"
          cat matrix.json

          MATRIX=$(cat matrix.json)
          if [[ -z "$MATRIX" || "$MATRIX" == "null" ]]; then
            echo "Matrix generation failed."
            exit 1
          fi

          echo "{matrix}={$MATRIX}" >> $GITHUB_OUTPUT

  integration_test:
    needs: generate_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate_matrix.outputs.matrix).include }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: ./.github/workflows/integration-test-steps.yml
        with:
          sqs_endpoint: ${{ matrix.sqs_endpoint }}
